services:
  forum-api:
    image: arsadisa/forum-api:${IMAGE_TAG:-latest}
    build:
      target: production
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      PGHOST: postgres_db
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGPORT: ${PGPORT}
      ACCESS_TOKEN_KEY: ${ACCESS_TOKEN_KEY}
      REFRESH_TOKEN_KEY: ${REFRESH_TOKEN_KEY}
      ACCESS_TOKEN_AGE: ${ACCESS_TOKEN_AGE}
    depends_on:
      postgres_db:
        condition: service_healthy
    restart: unless-stopped

  postgres_db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 5s
      timeout: 3s
      retries: 3
    restart: unless-stopped

volumes:
  postgres_data:
