name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: production
          push: true
          tags: arsadisa/forum-api:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Navigate to project directory and deploy latest changes
            cd ~/forum-api 

            # Pull latest code from repository
            git pull origin main

            # export variabel to compose
            export IMAGE_TAG=${{ github.sha }}

            # Pull image from Docker Hub
            docker compose pull forum-api

            # Run container
            docker compose up -d

            # Run database migrations
            docker compose exec -T forum-api npm run migrate up
